"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
<<<<<<< HEAD
Generated: 2026-05-26T09:05:38.026771+00:00
=======
Generated: 2026-05-26T09:46:14.819226+00:00
>>>>>>> upstream/main

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
<<<<<<< HEAD
from pyspark.sql.functions import col, current_timestamp, input_file_name, lit, to_date, broadcast
from pyspark.sql.types import DoubleType, StringType, DateType
import uuid
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read transactions and promotions data
    transactions_df = spark.read.format("delta").load(input_path + "/transactions_raw")
    promotions_df = spark.read.csv(input_path + "/promotions.csv", header=True, inferSchema=True)

    # Add metadata columns
    transactions_df = transactions_df.withColumn("ingestion_timestamp", current_timestamp()) \
                                      .withColumn("source_file_name", input_file_name()) \
                                      .withColumn("batch_id", lit(str(uuid.uuid4())))
    
    promotions_df = promotions_df.withColumn("ingestion_timestamp", current_timestamp()) \
                                 .withColumn("source_file_name", input_file_name()) \
                                 .withColumn("batch_id", lit(str(uuid.uuid4())))
    
    # Write Bronze tables partitioned by date
    transactions_df.write.partitionBy("transaction_date").parquet(output_path + "/bronze/transactions")
    promotions_df.write.partitionBy("run_date").parquet(output_path + "/bronze/promotions")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze tables with partition pruning
    transactions_df = spark.read.parquet(bronze_path + "/bronze/transactions").where(col("transaction_date") == run_date)
    promotions_df = spark.read.parquet(bronze_path + "/bronze/promotions").where(col("run_date") == run_date)
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(DoubleType())) \
                                     .withColumn("transaction_date", to_date(col("transaction_date"), "yyyy-MM-dd").cast(DateType()))
    promotions_df = promotions_df.withColumn("discount_pct", col("discount_pct").cast(DoubleType())) \
                                .withColumn("promo_cost", col("promo_cost").cast(DoubleType()))
    
    # Filter rows
    transactions_df = transactions_df.filter(col("amount") > 0) \
                                    .filter(col("transaction_id").isNotNull()) \
                                    .filter(col("customer_id").isNotNull())
    promotions_df = promotions_df.filter(col("discount_pct").between(0.0, 1.0)) \
                               .filter(col("channel").isin(['Email', 'SMS', 'Push']))
    
    # Deduplicate on transaction_id keeping latest by ingestion_timestamp
    transactions_df = transactions_df.withColumn("rank", (col("ingestion_timestamp").desc()).over(Window.partitionBy("transaction_id").orderBy("ingestion_timestamp"))) \
                                    .filter(col("rank") == 1).drop("rank")
    
    # Join with promotions on customer_id (broadcast hint, cache merchants)
    promotions_df = promotions_df.hint("broadcast")
    merchants_df = spark.read.parquet(merchants_path).cache()
    joined_df = transactions_df.join(promotions_df, transactions_df.customer_id == promotions_df.customer_id, "inner")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    joined_df = joined_df.withColumn("quality_flag", when(col("customer_id").isNotNull() & col("channel").isin(['Email', 'SMS', 'Push']), "CLEAN").otherwise("UNMATCHED"))
    
    # Write Silver table partitioned by date
    joined_df.write.partitionBy("transaction_date").parquet(output_path + "/silver")

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Marketing Attribution Pipeline").getOrCreate()
    
    # Paths and run date
    input_path = "/path/to/input"
    output_path = "/path/to/output"
    merchants_path = "/path/to/merchants"
    run_date = "2023-10-01"
    run_id = str(uuid.uuid4())
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, output_path, merchants_path, output_path, run_date)
=======
from pyspark.sql.functions import col, lit, coalesce, max as max_
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType())))
    
    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    deduped_df = (transactions_df.groupBy("transaction_id")
                 .agg(max_("ingestion_timestamp").alias("latest_timestamp")))
    transactions_df = transactions_df.join(deduped_df, on=["transaction_id", "ingestion_timestamp"], how="left_semi")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                   .option("inferSchema", "false")
                   .csv(merchants_path)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Join transactions with merchants
    enriched_df = (transactions_df.join(merchants_df, on="merchant_id", how="left")
                  .withColumn("quality_flag", coalesce(col("merchant_name"), lit("UNMATCHED"))))
    
    # Write as Parquet partitioned by date
    enriched_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions.csv"
    bronze_path = "s3://sigma-datatech/silver/transactions"
    merchants_path = "s3://sigma-datatech/bronze/merchants.csv"
    output_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform to Silver layer
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)
>>>>>>> upstream/main

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
<<<<<<< HEAD
from pyspark.sql.functions import col, sum, countDistinct, expr, broadcast, when, max, min, mode, collect_set
from pyspark.sql.types import StructType, StructField, DoubleType, StringType, DateType, IntegerType
import datetime
import os

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Ensure the output directory exists
    if not os.path.exists(gold_output_dir):
        os.makedirs(gold_output_dir)
    
    # Build the gold tables
    build_merchant_performance(spark, f"{silver_path}/merchants", f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, f"{silver_path}/customers", f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, f"{silver_path}/transactions", f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "gold_output_dir": gold_output_dir,
        "tables_built": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    spark.range(1).write.json(f"{gold_output_dir}/run_metadata", mode="overwrite")
    
def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
=======
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, first, last, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
>>>>>>> upstream/main
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
<<<<<<< HEAD
    # Aggregate metrics
    merchant_performance_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            countDistinct("transaction_id").alias("txn_count"),
            (count("transaction_id") - countWhen(col("status") == "COMPLETED")) / count("transaction_id") * 100
           .alias("failure_rate_pct")
        )
    
    # Write the gold table
    merchant_performance_df.write.partitionBy("date").mode("overwrite").delta(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
=======
    # Calculate total revenue and transaction count per merchant
    revenue_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(sum("amount").alias("total_revenue"), count("*").alias("txn_count"))
    
    # Calculate failure rate per merchant
    all_txns_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join revenue and failure rate calculations
    merchant_performance_df = revenue_df.join(failure_rate_df, ["merchant_id", "merchant_name", "category", "city", "date"], "left") \
        .select("merchant_id", "merchant_name", "category", "city", "date", "total_revenue", "txn_count", "failure_rate_pct")
    
    # Write output to Gold layer
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/merchant_performance")

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
>>>>>>> upstream/main
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
<<<<<<< HEAD
    # Aggregate metrics
    customer_ltv_df = completed_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("transaction_id").alias("total_txns"),
            expr("AVG(amount)").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write the gold table
    customer_ltv_df.write.mode("overwrite").delta(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Aggregate metrics
    daily_summary_df = silver_df.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("transaction_id").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count("transaction_id") - countWhen(col("status") == "COMPLETED")) / count("transaction_id") * 100
            .alias("failure_rate_pct")
        )
    
    # Add the run date
    daily_summary_df = daily_summary_df.withColumn("run_date", lit(run_date))
    
    # Write the gold table
    daily_summary_df.write.partitionBy("date").mode("overwrite").delta(output_path)
=======
    # Calculate total spent, total transactions, and preferred payment method per customer
    ltv_df = completed_df.groupBy("customer_id") \
       .agg(sum("amount").alias("total_spent"), count("*").alias("total_txns"), avg("amount").alias("avg_txn_value"), 
             first("transaction_date").alias("first_txn_date"), last("transaction_date").alias("last_txn_date"), 
             mode("payment_method").alias("preferred_payment_method"))
    
    # Write output to Gold layer
    ltv_df.write.mode("overwrite").parquet(output_path + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specific date
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate total revenue, total transactions, unique customers, and unique merchants
    total_revenue_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("date").agg(sum("amount").alias("total_revenue"), count("*").alias("total_txns"))
    
    unique_customers_df = silver_df.groupBy("date").agg(countDistinct("customer_id").alias("unique_customers"))
    
    unique_merchants_df = silver_df.groupBy("date").agg(countDistinct("merchant_id").alias("unique_merchants"))
    
    # Calculate failure rate
    all_txns_df = silver_df.groupBy("date").agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join all calculations
    daily_summary_df = total_revenue_df.join(unique_customers_df, "date", "inner") \
       .join(unique_merchants_df, "date", "inner") \
       .join(failure_rate_df, "date", "left") \
       .select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")
    
    # Write output to Gold layer
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/daily_summary")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define run metadata
    run_metadata = {"run_date": run_date, "silver_path": silver_path, "gold_output_dir": gold_output_dir}
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark Session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
>>>>>>> upstream/main
