"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:05:38.026771+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, current_timestamp, input_file_name, lit, to_date, broadcast
from pyspark.sql.types import DoubleType, StringType, DateType
import uuid
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read transactions and promotions data
    transactions_df = spark.read.format("delta").load(input_path + "/transactions_raw")
    promotions_df = spark.read.csv(input_path + "/promotions.csv", header=True, inferSchema=True)

    # Add metadata columns
    transactions_df = transactions_df.withColumn("ingestion_timestamp", current_timestamp()) \
                                      .withColumn("source_file_name", input_file_name()) \
                                      .withColumn("batch_id", lit(str(uuid.uuid4())))
    
    promotions_df = promotions_df.withColumn("ingestion_timestamp", current_timestamp()) \
                                 .withColumn("source_file_name", input_file_name()) \
                                 .withColumn("batch_id", lit(str(uuid.uuid4())))
    
    # Write Bronze tables partitioned by date
    transactions_df.write.partitionBy("transaction_date").parquet(output_path + "/bronze/transactions")
    promotions_df.write.partitionBy("run_date").parquet(output_path + "/bronze/promotions")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze tables with partition pruning
    transactions_df = spark.read.parquet(bronze_path + "/bronze/transactions").where(col("transaction_date") == run_date)
    promotions_df = spark.read.parquet(bronze_path + "/bronze/promotions").where(col("run_date") == run_date)
    
    # Cast columns to correct types
    transactions_df = transactions_df.withColumn("amount", col("amount").cast(DoubleType())) \
                                     .withColumn("transaction_date", to_date(col("transaction_date"), "yyyy-MM-dd").cast(DateType()))
    promotions_df = promotions_df.withColumn("discount_pct", col("discount_pct").cast(DoubleType())) \
                                .withColumn("promo_cost", col("promo_cost").cast(DoubleType()))
    
    # Filter rows
    transactions_df = transactions_df.filter(col("amount") > 0) \
                                    .filter(col("transaction_id").isNotNull()) \
                                    .filter(col("customer_id").isNotNull())
    promotions_df = promotions_df.filter(col("discount_pct").between(0.0, 1.0)) \
                               .filter(col("channel").isin(['Email', 'SMS', 'Push']))
    
    # Deduplicate on transaction_id keeping latest by ingestion_timestamp
    transactions_df = transactions_df.withColumn("rank", (col("ingestion_timestamp").desc()).over(Window.partitionBy("transaction_id").orderBy("ingestion_timestamp"))) \
                                    .filter(col("rank") == 1).drop("rank")
    
    # Join with promotions on customer_id (broadcast hint, cache merchants)
    promotions_df = promotions_df.hint("broadcast")
    merchants_df = spark.read.parquet(merchants_path).cache()
    joined_df = transactions_df.join(promotions_df, transactions_df.customer_id == promotions_df.customer_id, "inner")
    
    # Add quality_flag column (CLEAN or UNMATCHED)
    joined_df = joined_df.withColumn("quality_flag", when(col("customer_id").isNotNull() & col("channel").isin(['Email', 'SMS', 'Push']), "CLEAN").otherwise("UNMATCHED"))
    
    # Write Silver table partitioned by date
    joined_df.write.partitionBy("transaction_date").parquet(output_path + "/silver")

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Marketing Attribution Pipeline").getOrCreate()
    
    # Paths and run date
    input_path = "/path/to/input"
    output_path = "/path/to/output"
    merchants_path = "/path/to/merchants"
    run_date = "2023-10-01"
    run_id = str(uuid.uuid4())
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, output_path, run_date, run_id)
    
    # Transform Silver layer
    transform_silver(spark, output_path, merchants_path, output_path, run_date)

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, countDistinct, expr, broadcast, when, max, min, mode, collect_set
from pyspark.sql.types import StructType, StructField, DoubleType, StringType, DateType, IntegerType
import datetime
import os

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Ensure the output directory exists
    if not os.path.exists(gold_output_dir):
        os.makedirs(gold_output_dir)
    
    # Build the gold tables
    build_merchant_performance(spark, f"{silver_path}/merchants", f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, f"{silver_path}/customers", f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, f"{silver_path}/transactions", f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    run_metadata = {
        "run_date": run_date,
        "gold_output_dir": gold_output_dir,
        "tables_built": ["merchant_performance", "customer_ltv", "daily_summary"]
    }
    spark.range(1).write.json(f"{gold_output_dir}/run_metadata", mode="overwrite")
    
def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Aggregate metrics
    merchant_performance_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            countDistinct("transaction_id").alias("txn_count"),
            (count("transaction_id") - countWhen(col("status") == "COMPLETED")) / count("transaction_id") * 100
           .alias("failure_rate_pct")
        )
    
    # Write the gold table
    merchant_performance_df.write.partitionBy("date").mode("overwrite").delta(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Aggregate metrics
    customer_ltv_df = completed_df.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("transaction_id").alias("total_txns"),
            expr("AVG(amount)").alias("avg_txn_value"),
            min("transaction_date").alias("first_txn_date"),
            max("transaction_date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    
    # Write the gold table
    customer_ltv_df.write.mode("overwrite").delta(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the silver table
    silver_df = spark.read.format("delta").load(silver_path)
    
    # Aggregate metrics
    daily_summary_df = silver_df.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("transaction_id").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count("transaction_id") - countWhen(col("status") == "COMPLETED")) / count("transaction_id") * 100
            .alias("failure_rate_pct")
        )
    
    # Add the run date
    daily_summary_df = daily_summary_df.withColumn("run_date", lit(run_date))
    
    # Write the gold table
    daily_summary_df.write.partitionBy("date").mode("overwrite").delta(output_path)
