-- models/marts/mart_merchant_kpis.sql

WITH completed_transactions AS (
    SELECT
        merchant_id,
        SUM(amount) AS total_revenue,
        COUNT(*) AS total_transactions
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

failed_transactions AS (
    SELECT
        merchant_id,
        COUNT(*) AS failed_count
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'FAILED'
    GROUP BY
        merchant_id
),

avg_transaction_value AS (
    SELECT
        merchant_id,
        AVG(amount) AS avg_transaction_value
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

unique_customers AS (
    SELECT
        merchant_id,
        COUNT(DISTINCT customer_id) AS unique_customers
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

merchant_kpis AS (
    SELECT
        dm.merchant_id,
        dm.merchant_name,
        dm.category,
        dm.city,
        dm.onboarded_date,
        COALESCE(ct.total_revenue, 0) AS total_revenue,
        COALESCE(ct.total_transactions, 0) AS total_transactions,
        COALESCE(ft.failed_count, 0) AS failed_count,
        COALESCE(ct.total_transactions, 0) + COALESCE(ft.failed_count, 0) AS total_attempts,
        COALESCE(ct.total_transactions, 0) / NULLIF(COALESCE(ct.total_transactions, 0) + COALESCE(ft.failed_count, 0), 0) * 100 AS failure_rate_pct,
        COALESCE(atv.avg_transaction_value, 0) AS avg_transaction_value,
        COALESCE(uc.unique_customers, 0) AS unique_customers
    FROM
        {{ ref('dim_merchant') }} dm
        LEFT JOIN completed_transactions ct ON dm.merchant_id = ct.merchant_id
        LEFT JOIN failed_transactions ft ON dm.merchant_id = ft.merchant_id
        LEFT JOIN avg_transaction_value atv ON dm.merchant_id = atv.merchant_id
        LEFT JOIN unique_customers uc ON dm.merchant_id = uc.merchant_id
)

SELECT
    *
FROM
    merchant_kpis
```

```yaml
# models/marts/schema.yml

version: 2

models:
  - name: mart_merchant_kpis
    description: "Aggregated merchant KPIs including total revenue, total transactions, failed count, failure rate, average transaction value, and unique customers."
    columns:
      - name: merchant_id
        description: "Unique identifier for the merchant."
        tests:
          - not_null
          - unique
      - name: merchant_name
        description: "Name of the merchant."
        tests:
          - not_null
      - name: category
        description: "Category of the merchant."
        tests:
          - accepted_values:
              values: ["Food Delivery", "E-Commerce", "Entertainment", "Travel", "Grocery"]
      - name: city
        description: "City where the merchant is located."
        tests:
          - not_null
      - name: onboarded_date
        description: "Date when the merchant was onboarded."
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue generated by the merchant from completed transactions."
      - name: total_transactions
        description: "Total number of completed transactions by the merchant."
      - name: failed_count
        description: "Total number of failed transactions by the merchant."
      - name: total_attempts
        description: "Total number of transaction attempts by the merchant."
      - name: failure_rate_pct
        description: "Failure rate percentage of transactions by the merchant."
      - name: avg_transaction_value
        description: "Average transaction value for completed transactions by the merchant."
      - name: unique_customers
        description: "Number of unique customers who made completed transactions with the merchant."
