<<<<<<< HEAD
-- models/marts/mart_merchant_kpis.sql

WITH completed_transactions AS (
    SELECT
        merchant_id,
        SUM(amount) AS total_revenue,
        COUNT(*) AS total_transactions
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

failed_transactions AS (
    SELECT
        merchant_id,
        COUNT(*) AS failed_count
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'FAILED'
    GROUP BY
        merchant_id
),

avg_transaction_value AS (
    SELECT
        merchant_id,
        AVG(amount) AS avg_transaction_value
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

unique_customers AS (
    SELECT
        merchant_id,
        COUNT(DISTINCT customer_id) AS unique_customers
    FROM
        {{ ref('fact_transactions') }}
    WHERE
        status = 'COMPLETED'
    GROUP BY
        merchant_id
),

merchant_kpis AS (
    SELECT
        dm.merchant_id,
        dm.merchant_name,
        dm.category,
        dm.city,
        dm.onboarded_date,
        COALESCE(ct.total_revenue, 0) AS total_revenue,
        COALESCE(ct.total_transactions, 0) AS total_transactions,
        COALESCE(ft.failed_count, 0) AS failed_count,
        COALESCE(ct.total_transactions, 0) + COALESCE(ft.failed_count, 0) AS total_attempts,
        COALESCE(ct.total_transactions, 0) / NULLIF(COALESCE(ct.total_transactions, 0) + COALESCE(ft.failed_count, 0), 0) * 100 AS failure_rate_pct,
        COALESCE(atv.avg_transaction_value, 0) AS avg_transaction_value,
        COALESCE(uc.unique_customers, 0) AS unique_customers
    FROM
        {{ ref('dim_merchant') }} dm
        LEFT JOIN completed_transactions ct ON dm.merchant_id = ct.merchant_id
        LEFT JOIN failed_transactions ft ON dm.merchant_id = ft.merchant_id
        LEFT JOIN avg_transaction_value atv ON dm.merchant_id = atv.merchant_id
        LEFT JOIN unique_customers uc ON dm.merchant_id = uc.merchant_id
)

SELECT
    *
FROM
    merchant_kpis
```

```yaml
# models/marts/schema.yml

=======
WITH filtered_transactions AS (
    SELECT
        transaction_id,
        amount,
        status,
        merchant_id,
        customer_id,
        transaction_date,
        payment_method
    FROM {{ ref('stg_fact_transactions') }}
    WHERE status IN ('COMPLETED', 'FAILED')
),

merchant_details AS (
    SELECT
        merchant_id,
        merchant_name,
        category,
        city,
        onboarded_date
    FROM {{ ref('dim_merchant') }}
),

aggregated_metrics AS (
    SELECT
        ft.merchant_id,
        COUNT(ft.transaction_id) AS total_transactions,
        COUNT(CASE WHEN ft.status = 'FAILED' THEN 1 END) AS failed_count,
        SUM(CASE WHEN ft.status = 'COMPLETED' THEN ft.amount ELSE 0 END) AS total_revenue,
        AVG(CASE WHEN ft.status = 'COMPLETED' THEN ft.amount ELSE NULL END) AS avg_transaction_value,
        COUNT(DISTINCT ft.customer_id) AS unique_customers
    FROM filtered_transactions ft
    GROUP BY ft.merchant_id
)

SELECT
    md.merchant_id,
    md.merchant_name,
    md.category,
    md.city,
    md.onboarded_date,
    am.total_transactions,
    am.failed_count,
    am.total_revenue,
    am.avg_transaction_value,
    am.unique_customers,
    (am.failed_count::FLOAT / am.total_transactions) * 100 AS failure_rate_pct
FROM aggregated_metrics am
JOIN merchant_details md ON am.merchant_id = md.merchant_id
```

```yaml
>>>>>>> upstream/main
version: 2

models:
  - name: mart_merchant_kpis
    description: "Aggregated merchant KPIs including total revenue, total transactions, failed count, failure rate, average transaction value, and unique customers."
    columns:
      - name: merchant_id
        description: "Unique identifier for the merchant."
        tests:
          - not_null
          - unique
<<<<<<< HEAD
=======
          - relationships:
              to: ref('dim_merchant')
              field: merchant_id
>>>>>>> upstream/main
      - name: merchant_name
        description: "Name of the merchant."
        tests:
          - not_null
      - name: category
        description: "Category of the merchant."
        tests:
<<<<<<< HEAD
=======
          - not_null
>>>>>>> upstream/main
          - accepted_values:
              values: ["Food Delivery", "E-Commerce", "Entertainment", "Travel", "Grocery"]
      - name: city
        description: "City where the merchant is located."
        tests:
          - not_null
      - name: onboarded_date
        description: "Date when the merchant was onboarded."
        tests:
          - not_null
<<<<<<< HEAD
      - name: total_revenue
        description: "Total revenue generated by the merchant from completed transactions."
      - name: total_transactions
        description: "Total number of completed transactions by the merchant."
      - name: failed_count
        description: "Total number of failed transactions by the merchant."
      - name: total_attempts
        description: "Total number of transaction attempts by the merchant."
      - name: failure_rate_pct
        description: "Failure rate percentage of transactions by the merchant."
      - name: avg_transaction_value
        description: "Average transaction value for completed transactions by the merchant."
      - name: unique_customers
        description: "Number of unique customers who made completed transactions with the merchant."
=======
      - name: total_transactions
        description: "Total number of transactions for the merchant."
        tests:
          - not_null
      - name: failed_count
        description: "Number of failed transactions for the merchant."
        tests:
          - not_null
      - name: total_revenue
        description: "Total revenue from completed transactions for the merchant."
        tests:
          - not_null
      - name: avg_transaction_value
        description: "Average value of completed transactions for the merchant."
        tests:
          - not_null
      - name: unique_customers
        description: "Number of unique customers who made transactions with the merchant."
        tests:
          - not_null
      - name: failure_rate_pct
        description: "Failure rate percentage of transactions for the merchant."
>>>>>>> upstream/main
